@startuml
skinparam Linetype Ortho
left to right direction
actor Gast as g
actor Lid as l
actor Admin as a
rectangle "'Love Match' Mobile Dating app" {
    usecase uc1 as "UC1: App downloaden"
    usecase uc2 as "UC2: Hoofdscherm openen"
    usecase uc3 as "UC3: Account registreren"
    usecase uc4 as "UC4: Profiel aanmaken"
    usecase uc5 as "UC5: Profiel beheren"
    usecase uc6 as "UC6: Membership kopen"
    usecase uc7 as "UC7: Profielen swipen"
    usecase uc8 as "UC8: Profielen liken"
    usecase uc9 as "UC9: Match acties"
    usecase uc10 as "UC10: Beheren accounts"
    }
 g -- uc1
 g -- uc2
 g -- uc3
 l -- uc4
 l -- uc5
 l -- uc6
 l -- uc7
 l -- uc8
 l -- uc9
 a -- uc10
@enduml