name: CI .NET - DatingApp

on:
  push:
    branches:
    - Develop
  pull_request:
    branches:
    - main
  workflow_dispatch:
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        
    - name: Install Maui workloads
      run: dotnet workload restore LoveMatch/LoveMatch/LoveMatchProfileApi.sln
    - name: Restore dependencies
      run: dotnet restore LoveMatch/LoveMatch/LoveMatchProfileApi.sln
    - name: Build
      run: dotnet build LoveMatch/LoveMatch/LoveMatchProfileApi.sln --no-restore --configuration Release
    - name: Test
      run: dotnet test LoveMatch/LoveMatch/LoveMatchProfileApi.sln --no-build --configuration Release --verbosity normal
 
