name: CI .NET - WebApi

on:
  push:
    branches:
    - Develop
    - Develop---Tim
    paths-ignore:
      - .github/workflows/
  pull_request:
    branches:
    - main
    paths-ignore:
    - .github/workflows/
  workflow_dispatch:
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
  
    - name: Restore dependencies
      run: dotnet restore LoveMatchProfileApi/ProfileApi.csproj
    - name: Build
      run: dotnet build LoveMatchProfileApi/ProfileApi.csproj --no-restore --configuration Release --verbosity minimal
    - name: Test
      shell: pwsh
      run: dotnet test LoveMatchProfileApi.Tests/ProfileApi.Tests.csproj --configuration Release --verbosity minimal
 
