name: CI .NET - DatingApp

on:
  push:
    branches:
    - Develop
  pull_request:
    branches:
    - main
  workflow_dispatch:
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
  
    - name: Restore dependencies
      run: dotnet restore LoveMatch/LoveMatchProfileApi/ProfileApi.csproj
    - name: Build
      run: dotnet build LoveMatch/LoveMatchProfileApi/ProfileApi.csproj --no-restore --configuration Release --verbosity minimal
    - name: Test
      shell: pwsh
      run: dotnet test LoveMatchProfileApi.Tests.csproj --configuration Release --verbosity minimal
      working-directory: LoveMatch/LoveMatch/LoveMatchProfileApi.Tests
 
