name: Rise and grind

on: 
  schedule:
    - cron: "0 7 * * 0-6"
  workflow_dispatch:      

jobs:
  message:
    runs-on: ubuntu-latest

    steps:
      - name: Send message
        run: echo "Rise and Grind!!"
